package com.woniuxy.mapper;

import com.woniuxy.domain.SalesTree;
import com.woniuxy.domain.SalesTreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesTreeMapper {
	List findByUid(int uid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_tree
     *
     * @mbggenerated Sat Jan 05 13:36:43 CST 2019
     */
    int countByExample(SalesTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_tree
     *
     * @mbggenerated Sat Jan 05 13:36:43 CST 2019
     */
    int deleteByExample(SalesTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_tree
     *
     * @mbggenerated Sat Jan 05 13:36:43 CST 2019
     */
    int deleteByPrimaryKey(Integer treeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_tree
     *
     * @mbggenerated Sat Jan 05 13:36:43 CST 2019
     */
    int insert(SalesTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_tree
     *
     * @mbggenerated Sat Jan 05 13:36:43 CST 2019
     */
    int insertSelective(SalesTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_tree
     *
     * @mbggenerated Sat Jan 05 13:36:43 CST 2019
     */
    List<SalesTree> selectByExample(SalesTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_tree
     *
     * @mbggenerated Sat Jan 05 13:36:43 CST 2019
     */
    SalesTree selectByPrimaryKey(Integer treeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_tree
     *
     * @mbggenerated Sat Jan 05 13:36:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalesTree record, @Param("example") SalesTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_tree
     *
     * @mbggenerated Sat Jan 05 13:36:43 CST 2019
     */
    int updateByExample(@Param("record") SalesTree record, @Param("example") SalesTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_tree
     *
     * @mbggenerated Sat Jan 05 13:36:43 CST 2019
     */
    int updateByPrimaryKeySelective(SalesTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_tree
     *
     * @mbggenerated Sat Jan 05 13:36:43 CST 2019
     */
    int updateByPrimaryKey(SalesTree record);
}