package com.woniuxy.mapper;

import com.woniuxy.domain.SaleInfodetail;
import com.woniuxy.domain.SaleInfodetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleInfodetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_infodetail
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SaleInfodetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_infodetail
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SaleInfodetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_infodetail
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer infoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_infodetail
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SaleInfodetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_infodetail
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SaleInfodetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_infodetail
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SaleInfodetail> selectByExample(SaleInfodetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_infodetail
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SaleInfodetail selectByPrimaryKey(Integer infoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_infodetail
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SaleInfodetail record, @Param("example") SaleInfodetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_infodetail
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SaleInfodetail record, @Param("example") SaleInfodetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_infodetail
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SaleInfodetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_infodetail
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SaleInfodetail record);
}