package com.woniuxy.mapper;

import com.woniuxy.domain.SalesCourse;
import com.woniuxy.domain.SalesCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_course
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SalesCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_course
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SalesCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_course
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer courseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_course
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SalesCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_course
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SalesCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_course
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SalesCourse> selectByExample(SalesCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_course
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SalesCourse selectByPrimaryKey(Integer courseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_course
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalesCourse record, @Param("example") SalesCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_course
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SalesCourse record, @Param("example") SalesCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_course
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SalesCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_course
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SalesCourse record);
}