package com.woniuxy.mapper;

import com.woniuxy.domain.SalesUserinfo;
import com.woniuxy.domain.SalesUserinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SalesUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_userinfo
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SalesUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_userinfo
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SalesUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_userinfo
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_userinfo
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SalesUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_userinfo
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SalesUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_userinfo
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SalesUserinfo> selectByExample(SalesUserinfoExample example,RowBounds rb);
    
    List<SalesUserinfo> selectByExample(SalesUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_userinfo
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SalesUserinfo selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_userinfo
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalesUserinfo record, @Param("example") SalesUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_userinfo
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SalesUserinfo record, @Param("example") SalesUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_userinfo
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SalesUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_userinfo
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SalesUserinfo record);
}