package com.woniuxy.mapper;

import com.woniuxy.domain.SalesCity;
import com.woniuxy.domain.SalesCityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_city
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SalesCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_city
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SalesCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_city
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_city
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SalesCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_city
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SalesCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_city
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SalesCity> selectByExample(SalesCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_city
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SalesCity selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_city
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalesCity record, @Param("example") SalesCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_city
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SalesCity record, @Param("example") SalesCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_city
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SalesCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_city
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SalesCity record);
}