package com.woniuxy.mapper;

import com.woniuxy.domain.SalesDegree;
import com.woniuxy.domain.SalesDegreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesDegreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_degree
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SalesDegreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_degree
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SalesDegreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_degree
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer degreeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_degree
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SalesDegree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_degree
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SalesDegree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_degree
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SalesDegree> selectByExample(SalesDegreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_degree
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SalesDegree selectByPrimaryKey(Integer degreeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_degree
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalesDegree record, @Param("example") SalesDegreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_degree
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SalesDegree record, @Param("example") SalesDegreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_degree
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SalesDegree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_degree
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SalesDegree record);
}