package com.woniuxy.mapper;

import com.woniuxy.domain.SalesComefrom;
import com.woniuxy.domain.SalesComefromExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesComefromMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_comefrom
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SalesComefromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_comefrom
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SalesComefromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_comefrom
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer comefromid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_comefrom
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SalesComefrom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_comefrom
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SalesComefrom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_comefrom
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SalesComefrom> selectByExample(SalesComefromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_comefrom
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SalesComefrom selectByPrimaryKey(Integer comefromid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_comefrom
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalesComefrom record, @Param("example") SalesComefromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_comefrom
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SalesComefrom record, @Param("example") SalesComefromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_comefrom
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SalesComefrom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_comefrom
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SalesComefrom record);
}