package com.woniuxy.mapper;

import com.woniuxy.domain.SaleInfo;
import com.woniuxy.domain.SaleInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SaleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SaleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SaleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer infoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SaleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SaleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SaleInfo> selectByExample(SaleInfoExample example,RowBounds rb);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SaleInfo selectByPrimaryKey(Integer infoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SaleInfo record, @Param("example") SaleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SaleInfo record, @Param("example") SaleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SaleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SaleInfo record);
}