package com.woniuxy.mapper;

import com.woniuxy.domain.SalesInfotype;
import com.woniuxy.domain.SalesInfotypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesInfotypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SalesInfotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SalesInfotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer infotypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SalesInfotype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SalesInfotype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SalesInfotype> selectByExample(SalesInfotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SalesInfotype selectByPrimaryKey(Integer infotypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalesInfotype record, @Param("example") SalesInfotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SalesInfotype record, @Param("example") SalesInfotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SalesInfotype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SalesInfotype record);
}