package com.woniuxy.mapper;

import com.woniuxy.domain.SalesArea;
import com.woniuxy.domain.SalesAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_area
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SalesAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_area
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SalesAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_area
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_area
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SalesArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_area
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SalesArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_area
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SalesArea> selectByExample(SalesAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_area
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SalesArea selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_area
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalesArea record, @Param("example") SalesAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_area
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SalesArea record, @Param("example") SalesAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_area
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SalesArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_area
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SalesArea record);
}