package com.woniuxy.mapper;

import com.woniuxy.domain.SalesResult;
import com.woniuxy.domain.SalesResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_result
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SalesResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_result
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SalesResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_result
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer resultid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_result
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SalesResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_result
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SalesResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_result
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SalesResult> selectByExample(SalesResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_result
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SalesResult selectByPrimaryKey(Integer resultid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_result
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalesResult record, @Param("example") SalesResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_result
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SalesResult record, @Param("example") SalesResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_result
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SalesResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_result
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SalesResult record);
}