package com.woniuxy.mapper;

import com.woniuxy.domain.SalesReturn;
import com.woniuxy.domain.SalesReturnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_return
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SalesReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_return
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SalesReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_return
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer returnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_return
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SalesReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_return
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SalesReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_return
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SalesReturn> selectByExample(SalesReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_return
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SalesReturn selectByPrimaryKey(Integer returnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_return
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalesReturn record, @Param("example") SalesReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_return
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SalesReturn record, @Param("example") SalesReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_return
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SalesReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_return
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SalesReturn record);
}