package com.woniuxy.mapper;

import com.woniuxy.domain.SalesProvince;
import com.woniuxy.domain.SalesProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_province
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SalesProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_province
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SalesProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_province
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_province
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SalesProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_province
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SalesProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_province
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SalesProvince> selectByExample(SalesProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_province
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SalesProvince selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_province
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalesProvince record, @Param("example") SalesProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_province
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SalesProvince record, @Param("example") SalesProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_province
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SalesProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_province
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SalesProvince record);
}