package com.woniuxy.mapper;

import com.woniuxy.domain.SalesMessage;
import com.woniuxy.domain.SalesMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SalesMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SalesMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SalesMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SalesMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SalesMessage> selectByExampleWithBLOBs(SalesMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SalesMessage> selectByExample(SalesMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SalesMessage selectByPrimaryKey(Integer messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalesMessage record, @Param("example") SalesMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SalesMessage record, @Param("example") SalesMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SalesMessage record, @Param("example") SalesMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SalesMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(SalesMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SalesMessage record);
}