package com.woniuxy.mapper;

import com.woniuxy.domain.SalesRelatedperson;
import com.woniuxy.domain.SalesRelatedpersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesRelatedpersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_relatedperson
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SalesRelatedpersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_relatedperson
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SalesRelatedpersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_relatedperson
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer relatedpersonid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_relatedperson
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SalesRelatedperson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_relatedperson
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SalesRelatedperson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_relatedperson
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SalesRelatedperson> selectByExample(SalesRelatedpersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_relatedperson
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SalesRelatedperson selectByPrimaryKey(Integer relatedpersonid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_relatedperson
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalesRelatedperson record, @Param("example") SalesRelatedpersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_relatedperson
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SalesRelatedperson record, @Param("example") SalesRelatedpersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_relatedperson
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SalesRelatedperson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_relatedperson
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SalesRelatedperson record);
}