package com.woniuxy.mapper;

import com.woniuxy.domain.SalesUserMessage;
import com.woniuxy.domain.SalesUserMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesUserMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_user_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SalesUserMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_user_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SalesUserMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_user_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SalesUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_user_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SalesUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_user_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SalesUserMessage> selectByExample(SalesUserMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_user_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalesUserMessage record, @Param("example") SalesUserMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_user_message
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SalesUserMessage record, @Param("example") SalesUserMessageExample example);
}