package com.woniuxy.mapper;

import com.woniuxy.domain.SaleVisit;
import com.woniuxy.domain.SaleVisitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_visit
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int countByExample(SaleVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_visit
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByExample(SaleVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_visit
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int deleteByPrimaryKey(Integer visitid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_visit
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insert(SaleVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_visit
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int insertSelective(SaleVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_visit
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    List<SaleVisit> selectByExample(SaleVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_visit
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    SaleVisit selectByPrimaryKey(Integer visitid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_visit
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SaleVisit record, @Param("example") SaleVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_visit
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByExample(@Param("record") SaleVisit record, @Param("example") SaleVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_visit
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKeySelective(SaleVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_visit
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    int updateByPrimaryKey(SaleVisit record);
}