package com.woniuxy.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SaleInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public SaleInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andInfoidIsNull() {
            addCriterion("infoid is null");
            return (Criteria) this;
        }

        public Criteria andInfoidIsNotNull() {
            addCriterion("infoid is not null");
            return (Criteria) this;
        }

        public Criteria andInfoidEqualTo(Integer value) {
            addCriterion("infoid =", value, "infoid");
            return (Criteria) this;
        }

        public Criteria andInfoidNotEqualTo(Integer value) {
            addCriterion("infoid <>", value, "infoid");
            return (Criteria) this;
        }

        public Criteria andInfoidGreaterThan(Integer value) {
            addCriterion("infoid >", value, "infoid");
            return (Criteria) this;
        }

        public Criteria andInfoidGreaterThanOrEqualTo(Integer value) {
            addCriterion("infoid >=", value, "infoid");
            return (Criteria) this;
        }

        public Criteria andInfoidLessThan(Integer value) {
            addCriterion("infoid <", value, "infoid");
            return (Criteria) this;
        }

        public Criteria andInfoidLessThanOrEqualTo(Integer value) {
            addCriterion("infoid <=", value, "infoid");
            return (Criteria) this;
        }

        public Criteria andInfoidIn(List<Integer> values) {
            addCriterion("infoid in", values, "infoid");
            return (Criteria) this;
        }

        public Criteria andInfoidNotIn(List<Integer> values) {
            addCriterion("infoid not in", values, "infoid");
            return (Criteria) this;
        }

        public Criteria andInfoidBetween(Integer value1, Integer value2) {
            addCriterion("infoid between", value1, value2, "infoid");
            return (Criteria) this;
        }

        public Criteria andInfoidNotBetween(Integer value1, Integer value2) {
            addCriterion("infoid not between", value1, value2, "infoid");
            return (Criteria) this;
        }

        public Criteria andInfonameIsNull() {
            addCriterion("infoname is null");
            return (Criteria) this;
        }

        public Criteria andInfonameIsNotNull() {
            addCriterion("infoname is not null");
            return (Criteria) this;
        }

        public Criteria andInfonameEqualTo(String value) {
            addCriterion("infoname =", value, "infoname");
            return (Criteria) this;
        }

        public Criteria andInfonameNotEqualTo(String value) {
            addCriterion("infoname <>", value, "infoname");
            return (Criteria) this;
        }

        public Criteria andInfonameGreaterThan(String value) {
            addCriterion("infoname >", value, "infoname");
            return (Criteria) this;
        }

        public Criteria andInfonameGreaterThanOrEqualTo(String value) {
            addCriterion("infoname >=", value, "infoname");
            return (Criteria) this;
        }

        public Criteria andInfonameLessThan(String value) {
            addCriterion("infoname <", value, "infoname");
            return (Criteria) this;
        }

        public Criteria andInfonameLessThanOrEqualTo(String value) {
            addCriterion("infoname <=", value, "infoname");
            return (Criteria) this;
        }

        public Criteria andInfonameLike(String value) {
            addCriterion("infoname like", value, "infoname");
            return (Criteria) this;
        }

        public Criteria andInfonameNotLike(String value) {
            addCriterion("infoname not like", value, "infoname");
            return (Criteria) this;
        }

        public Criteria andInfonameIn(List<String> values) {
            addCriterion("infoname in", values, "infoname");
            return (Criteria) this;
        }

        public Criteria andInfonameNotIn(List<String> values) {
            addCriterion("infoname not in", values, "infoname");
            return (Criteria) this;
        }

        public Criteria andInfonameBetween(String value1, String value2) {
            addCriterion("infoname between", value1, value2, "infoname");
            return (Criteria) this;
        }

        public Criteria andInfonameNotBetween(String value1, String value2) {
            addCriterion("infoname not between", value1, value2, "infoname");
            return (Criteria) this;
        }

        public Criteria andInfonamepinyinIsNull() {
            addCriterion("infonamepinyin is null");
            return (Criteria) this;
        }

        public Criteria andInfonamepinyinIsNotNull() {
            addCriterion("infonamepinyin is not null");
            return (Criteria) this;
        }

        public Criteria andInfonamepinyinEqualTo(String value) {
            addCriterion("infonamepinyin =", value, "infonamepinyin");
            return (Criteria) this;
        }

        public Criteria andInfonamepinyinNotEqualTo(String value) {
            addCriterion("infonamepinyin <>", value, "infonamepinyin");
            return (Criteria) this;
        }

        public Criteria andInfonamepinyinGreaterThan(String value) {
            addCriterion("infonamepinyin >", value, "infonamepinyin");
            return (Criteria) this;
        }

        public Criteria andInfonamepinyinGreaterThanOrEqualTo(String value) {
            addCriterion("infonamepinyin >=", value, "infonamepinyin");
            return (Criteria) this;
        }

        public Criteria andInfonamepinyinLessThan(String value) {
            addCriterion("infonamepinyin <", value, "infonamepinyin");
            return (Criteria) this;
        }

        public Criteria andInfonamepinyinLessThanOrEqualTo(String value) {
            addCriterion("infonamepinyin <=", value, "infonamepinyin");
            return (Criteria) this;
        }

        public Criteria andInfonamepinyinLike(String value) {
            addCriterion("infonamepinyin like", value, "infonamepinyin");
            return (Criteria) this;
        }

        public Criteria andInfonamepinyinNotLike(String value) {
            addCriterion("infonamepinyin not like", value, "infonamepinyin");
            return (Criteria) this;
        }

        public Criteria andInfonamepinyinIn(List<String> values) {
            addCriterion("infonamepinyin in", values, "infonamepinyin");
            return (Criteria) this;
        }

        public Criteria andInfonamepinyinNotIn(List<String> values) {
            addCriterion("infonamepinyin not in", values, "infonamepinyin");
            return (Criteria) this;
        }

        public Criteria andInfonamepinyinBetween(String value1, String value2) {
            addCriterion("infonamepinyin between", value1, value2, "infonamepinyin");
            return (Criteria) this;
        }

        public Criteria andInfonamepinyinNotBetween(String value1, String value2) {
            addCriterion("infonamepinyin not between", value1, value2, "infonamepinyin");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Boolean value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Boolean value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Boolean value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Boolean value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Boolean value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Boolean value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Boolean> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Boolean> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Boolean value1, Boolean value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Boolean value1, Boolean value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andDegreeidIsNull() {
            addCriterion("degreeid is null");
            return (Criteria) this;
        }

        public Criteria andDegreeidIsNotNull() {
            addCriterion("degreeid is not null");
            return (Criteria) this;
        }

        public Criteria andDegreeidEqualTo(Integer value) {
            addCriterion("degreeid =", value, "degreeid");
            return (Criteria) this;
        }

        public Criteria andDegreeidNotEqualTo(Integer value) {
            addCriterion("degreeid <>", value, "degreeid");
            return (Criteria) this;
        }

        public Criteria andDegreeidGreaterThan(Integer value) {
            addCriterion("degreeid >", value, "degreeid");
            return (Criteria) this;
        }

        public Criteria andDegreeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("degreeid >=", value, "degreeid");
            return (Criteria) this;
        }

        public Criteria andDegreeidLessThan(Integer value) {
            addCriterion("degreeid <", value, "degreeid");
            return (Criteria) this;
        }

        public Criteria andDegreeidLessThanOrEqualTo(Integer value) {
            addCriterion("degreeid <=", value, "degreeid");
            return (Criteria) this;
        }

        public Criteria andDegreeidIn(List<Integer> values) {
            addCriterion("degreeid in", values, "degreeid");
            return (Criteria) this;
        }

        public Criteria andDegreeidNotIn(List<Integer> values) {
            addCriterion("degreeid not in", values, "degreeid");
            return (Criteria) this;
        }

        public Criteria andDegreeidBetween(Integer value1, Integer value2) {
            addCriterion("degreeid between", value1, value2, "degreeid");
            return (Criteria) this;
        }

        public Criteria andDegreeidNotBetween(Integer value1, Integer value2) {
            addCriterion("degreeid not between", value1, value2, "degreeid");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("tel is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("tel is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("tel =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("tel <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("tel >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("tel >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("tel <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("tel <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("tel like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("tel not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("tel in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("tel not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("tel between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("tel not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andComefromidIsNull() {
            addCriterion("comefromid is null");
            return (Criteria) this;
        }

        public Criteria andComefromidIsNotNull() {
            addCriterion("comefromid is not null");
            return (Criteria) this;
        }

        public Criteria andComefromidEqualTo(Integer value) {
            addCriterion("comefromid =", value, "comefromid");
            return (Criteria) this;
        }

        public Criteria andComefromidNotEqualTo(Integer value) {
            addCriterion("comefromid <>", value, "comefromid");
            return (Criteria) this;
        }

        public Criteria andComefromidGreaterThan(Integer value) {
            addCriterion("comefromid >", value, "comefromid");
            return (Criteria) this;
        }

        public Criteria andComefromidGreaterThanOrEqualTo(Integer value) {
            addCriterion("comefromid >=", value, "comefromid");
            return (Criteria) this;
        }

        public Criteria andComefromidLessThan(Integer value) {
            addCriterion("comefromid <", value, "comefromid");
            return (Criteria) this;
        }

        public Criteria andComefromidLessThanOrEqualTo(Integer value) {
            addCriterion("comefromid <=", value, "comefromid");
            return (Criteria) this;
        }

        public Criteria andComefromidIn(List<Integer> values) {
            addCriterion("comefromid in", values, "comefromid");
            return (Criteria) this;
        }

        public Criteria andComefromidNotIn(List<Integer> values) {
            addCriterion("comefromid not in", values, "comefromid");
            return (Criteria) this;
        }

        public Criteria andComefromidBetween(Integer value1, Integer value2) {
            addCriterion("comefromid between", value1, value2, "comefromid");
            return (Criteria) this;
        }

        public Criteria andComefromidNotBetween(Integer value1, Integer value2) {
            addCriterion("comefromid not between", value1, value2, "comefromid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidIsNull() {
            addCriterion("infotypeid is null");
            return (Criteria) this;
        }

        public Criteria andInfotypeidIsNotNull() {
            addCriterion("infotypeid is not null");
            return (Criteria) this;
        }

        public Criteria andInfotypeidEqualTo(Integer value) {
            addCriterion("infotypeid =", value, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidNotEqualTo(Integer value) {
            addCriterion("infotypeid <>", value, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidGreaterThan(Integer value) {
            addCriterion("infotypeid >", value, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("infotypeid >=", value, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidLessThan(Integer value) {
            addCriterion("infotypeid <", value, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidLessThanOrEqualTo(Integer value) {
            addCriterion("infotypeid <=", value, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidIn(List<Integer> values) {
            addCriterion("infotypeid in", values, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidNotIn(List<Integer> values) {
            addCriterion("infotypeid not in", values, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidBetween(Integer value1, Integer value2) {
            addCriterion("infotypeid between", value1, value2, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("infotypeid not between", value1, value2, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andReturndateIsNull() {
            addCriterion("returndate is null");
            return (Criteria) this;
        }

        public Criteria andReturndateIsNotNull() {
            addCriterion("returndate is not null");
            return (Criteria) this;
        }

        public Criteria andReturndateEqualTo(Date value) {
            addCriterionForJDBCDate("returndate =", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateNotEqualTo(Date value) {
            addCriterionForJDBCDate("returndate <>", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateGreaterThan(Date value) {
            addCriterionForJDBCDate("returndate >", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("returndate >=", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateLessThan(Date value) {
            addCriterionForJDBCDate("returndate <", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("returndate <=", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateIn(List<Date> values) {
            addCriterionForJDBCDate("returndate in", values, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateNotIn(List<Date> values) {
            addCriterionForJDBCDate("returndate not in", values, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("returndate between", value1, value2, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("returndate not between", value1, value2, "returndate");
            return (Criteria) this;
        }

        public Criteria andBeforepeopleIsNull() {
            addCriterion("beforepeople is null");
            return (Criteria) this;
        }

        public Criteria andBeforepeopleIsNotNull() {
            addCriterion("beforepeople is not null");
            return (Criteria) this;
        }

        public Criteria andBeforepeopleEqualTo(Integer value) {
            addCriterion("beforepeople =", value, "beforepeople");
            return (Criteria) this;
        }

        public Criteria andBeforepeopleNotEqualTo(Integer value) {
            addCriterion("beforepeople <>", value, "beforepeople");
            return (Criteria) this;
        }

        public Criteria andBeforepeopleGreaterThan(Integer value) {
            addCriterion("beforepeople >", value, "beforepeople");
            return (Criteria) this;
        }

        public Criteria andBeforepeopleGreaterThanOrEqualTo(Integer value) {
            addCriterion("beforepeople >=", value, "beforepeople");
            return (Criteria) this;
        }

        public Criteria andBeforepeopleLessThan(Integer value) {
            addCriterion("beforepeople <", value, "beforepeople");
            return (Criteria) this;
        }

        public Criteria andBeforepeopleLessThanOrEqualTo(Integer value) {
            addCriterion("beforepeople <=", value, "beforepeople");
            return (Criteria) this;
        }

        public Criteria andBeforepeopleIn(List<Integer> values) {
            addCriterion("beforepeople in", values, "beforepeople");
            return (Criteria) this;
        }

        public Criteria andBeforepeopleNotIn(List<Integer> values) {
            addCriterion("beforepeople not in", values, "beforepeople");
            return (Criteria) this;
        }

        public Criteria andBeforepeopleBetween(Integer value1, Integer value2) {
            addCriterion("beforepeople between", value1, value2, "beforepeople");
            return (Criteria) this;
        }

        public Criteria andBeforepeopleNotBetween(Integer value1, Integer value2) {
            addCriterion("beforepeople not between", value1, value2, "beforepeople");
            return (Criteria) this;
        }

        public Criteria andAfterpeopleIsNull() {
            addCriterion("afterpeople is null");
            return (Criteria) this;
        }

        public Criteria andAfterpeopleIsNotNull() {
            addCriterion("afterpeople is not null");
            return (Criteria) this;
        }

        public Criteria andAfterpeopleEqualTo(Integer value) {
            addCriterion("afterpeople =", value, "afterpeople");
            return (Criteria) this;
        }

        public Criteria andAfterpeopleNotEqualTo(Integer value) {
            addCriterion("afterpeople <>", value, "afterpeople");
            return (Criteria) this;
        }

        public Criteria andAfterpeopleGreaterThan(Integer value) {
            addCriterion("afterpeople >", value, "afterpeople");
            return (Criteria) this;
        }

        public Criteria andAfterpeopleGreaterThanOrEqualTo(Integer value) {
            addCriterion("afterpeople >=", value, "afterpeople");
            return (Criteria) this;
        }

        public Criteria andAfterpeopleLessThan(Integer value) {
            addCriterion("afterpeople <", value, "afterpeople");
            return (Criteria) this;
        }

        public Criteria andAfterpeopleLessThanOrEqualTo(Integer value) {
            addCriterion("afterpeople <=", value, "afterpeople");
            return (Criteria) this;
        }

        public Criteria andAfterpeopleIn(List<Integer> values) {
            addCriterion("afterpeople in", values, "afterpeople");
            return (Criteria) this;
        }

        public Criteria andAfterpeopleNotIn(List<Integer> values) {
            addCriterion("afterpeople not in", values, "afterpeople");
            return (Criteria) this;
        }

        public Criteria andAfterpeopleBetween(Integer value1, Integer value2) {
            addCriterion("afterpeople between", value1, value2, "afterpeople");
            return (Criteria) this;
        }

        public Criteria andAfterpeopleNotBetween(Integer value1, Integer value2) {
            addCriterion("afterpeople not between", value1, value2, "afterpeople");
            return (Criteria) this;
        }

        public Criteria andBeforetmkIsNull() {
            addCriterion("beforetmk is null");
            return (Criteria) this;
        }

        public Criteria andBeforetmkIsNotNull() {
            addCriterion("beforetmk is not null");
            return (Criteria) this;
        }

        public Criteria andBeforetmkEqualTo(Integer value) {
            addCriterion("beforetmk =", value, "beforetmk");
            return (Criteria) this;
        }

        public Criteria andBeforetmkNotEqualTo(Integer value) {
            addCriterion("beforetmk <>", value, "beforetmk");
            return (Criteria) this;
        }

        public Criteria andBeforetmkGreaterThan(Integer value) {
            addCriterion("beforetmk >", value, "beforetmk");
            return (Criteria) this;
        }

        public Criteria andBeforetmkGreaterThanOrEqualTo(Integer value) {
            addCriterion("beforetmk >=", value, "beforetmk");
            return (Criteria) this;
        }

        public Criteria andBeforetmkLessThan(Integer value) {
            addCriterion("beforetmk <", value, "beforetmk");
            return (Criteria) this;
        }

        public Criteria andBeforetmkLessThanOrEqualTo(Integer value) {
            addCriterion("beforetmk <=", value, "beforetmk");
            return (Criteria) this;
        }

        public Criteria andBeforetmkIn(List<Integer> values) {
            addCriterion("beforetmk in", values, "beforetmk");
            return (Criteria) this;
        }

        public Criteria andBeforetmkNotIn(List<Integer> values) {
            addCriterion("beforetmk not in", values, "beforetmk");
            return (Criteria) this;
        }

        public Criteria andBeforetmkBetween(Integer value1, Integer value2) {
            addCriterion("beforetmk between", value1, value2, "beforetmk");
            return (Criteria) this;
        }

        public Criteria andBeforetmkNotBetween(Integer value1, Integer value2) {
            addCriterion("beforetmk not between", value1, value2, "beforetmk");
            return (Criteria) this;
        }

        public Criteria andReturnidIsNull() {
            addCriterion("returnid is null");
            return (Criteria) this;
        }

        public Criteria andReturnidIsNotNull() {
            addCriterion("returnid is not null");
            return (Criteria) this;
        }

        public Criteria andReturnidEqualTo(Integer value) {
            addCriterion("returnid =", value, "returnid");
            return (Criteria) this;
        }

        public Criteria andReturnidNotEqualTo(Integer value) {
            addCriterion("returnid <>", value, "returnid");
            return (Criteria) this;
        }

        public Criteria andReturnidGreaterThan(Integer value) {
            addCriterion("returnid >", value, "returnid");
            return (Criteria) this;
        }

        public Criteria andReturnidGreaterThanOrEqualTo(Integer value) {
            addCriterion("returnid >=", value, "returnid");
            return (Criteria) this;
        }

        public Criteria andReturnidLessThan(Integer value) {
            addCriterion("returnid <", value, "returnid");
            return (Criteria) this;
        }

        public Criteria andReturnidLessThanOrEqualTo(Integer value) {
            addCriterion("returnid <=", value, "returnid");
            return (Criteria) this;
        }

        public Criteria andReturnidIn(List<Integer> values) {
            addCriterion("returnid in", values, "returnid");
            return (Criteria) this;
        }

        public Criteria andReturnidNotIn(List<Integer> values) {
            addCriterion("returnid not in", values, "returnid");
            return (Criteria) this;
        }

        public Criteria andReturnidBetween(Integer value1, Integer value2) {
            addCriterion("returnid between", value1, value2, "returnid");
            return (Criteria) this;
        }

        public Criteria andReturnidNotBetween(Integer value1, Integer value2) {
            addCriterion("returnid not between", value1, value2, "returnid");
            return (Criteria) this;
        }

        public Criteria andInfodateIsNull() {
            addCriterion("infodate is null");
            return (Criteria) this;
        }

        public Criteria andInfodateIsNotNull() {
            addCriterion("infodate is not null");
            return (Criteria) this;
        }

        public Criteria andInfodateEqualTo(Date value) {
            addCriterionForJDBCDate("infodate =", value, "infodate");
            return (Criteria) this;
        }

        public Criteria andInfodateNotEqualTo(Date value) {
            addCriterionForJDBCDate("infodate <>", value, "infodate");
            return (Criteria) this;
        }

        public Criteria andInfodateGreaterThan(Date value) {
            addCriterionForJDBCDate("infodate >", value, "infodate");
            return (Criteria) this;
        }

        public Criteria andInfodateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("infodate >=", value, "infodate");
            return (Criteria) this;
        }

        public Criteria andInfodateLessThan(Date value) {
            addCriterionForJDBCDate("infodate <", value, "infodate");
            return (Criteria) this;
        }

        public Criteria andInfodateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("infodate <=", value, "infodate");
            return (Criteria) this;
        }

        public Criteria andInfodateIn(List<Date> values) {
            addCriterionForJDBCDate("infodate in", values, "infodate");
            return (Criteria) this;
        }

        public Criteria andInfodateNotIn(List<Date> values) {
            addCriterionForJDBCDate("infodate not in", values, "infodate");
            return (Criteria) this;
        }

        public Criteria andInfodateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("infodate between", value1, value2, "infodate");
            return (Criteria) this;
        }

        public Criteria andInfodateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("infodate not between", value1, value2, "infodate");
            return (Criteria) this;
        }

        public Criteria andDistributiondateIsNull() {
            addCriterion("distributiondate is null");
            return (Criteria) this;
        }

        public Criteria andDistributiondateIsNotNull() {
            addCriterion("distributiondate is not null");
            return (Criteria) this;
        }

        public Criteria andDistributiondateEqualTo(Date value) {
            addCriterionForJDBCDate("distributiondate =", value, "distributiondate");
            return (Criteria) this;
        }

        public Criteria andDistributiondateNotEqualTo(Date value) {
            addCriterionForJDBCDate("distributiondate <>", value, "distributiondate");
            return (Criteria) this;
        }

        public Criteria andDistributiondateGreaterThan(Date value) {
            addCriterionForJDBCDate("distributiondate >", value, "distributiondate");
            return (Criteria) this;
        }

        public Criteria andDistributiondateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("distributiondate >=", value, "distributiondate");
            return (Criteria) this;
        }

        public Criteria andDistributiondateLessThan(Date value) {
            addCriterionForJDBCDate("distributiondate <", value, "distributiondate");
            return (Criteria) this;
        }

        public Criteria andDistributiondateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("distributiondate <=", value, "distributiondate");
            return (Criteria) this;
        }

        public Criteria andDistributiondateIn(List<Date> values) {
            addCriterionForJDBCDate("distributiondate in", values, "distributiondate");
            return (Criteria) this;
        }

        public Criteria andDistributiondateNotIn(List<Date> values) {
            addCriterionForJDBCDate("distributiondate not in", values, "distributiondate");
            return (Criteria) this;
        }

        public Criteria andDistributiondateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("distributiondate between", value1, value2, "distributiondate");
            return (Criteria) this;
        }

        public Criteria andDistributiondateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("distributiondate not between", value1, value2, "distributiondate");
            return (Criteria) this;
        }

        public Criteria andResultidIsNull() {
            addCriterion("resultid is null");
            return (Criteria) this;
        }

        public Criteria andResultidIsNotNull() {
            addCriterion("resultid is not null");
            return (Criteria) this;
        }

        public Criteria andResultidEqualTo(Integer value) {
            addCriterion("resultid =", value, "resultid");
            return (Criteria) this;
        }

        public Criteria andResultidNotEqualTo(Integer value) {
            addCriterion("resultid <>", value, "resultid");
            return (Criteria) this;
        }

        public Criteria andResultidGreaterThan(Integer value) {
            addCriterion("resultid >", value, "resultid");
            return (Criteria) this;
        }

        public Criteria andResultidGreaterThanOrEqualTo(Integer value) {
            addCriterion("resultid >=", value, "resultid");
            return (Criteria) this;
        }

        public Criteria andResultidLessThan(Integer value) {
            addCriterion("resultid <", value, "resultid");
            return (Criteria) this;
        }

        public Criteria andResultidLessThanOrEqualTo(Integer value) {
            addCriterion("resultid <=", value, "resultid");
            return (Criteria) this;
        }

        public Criteria andResultidIn(List<Integer> values) {
            addCriterion("resultid in", values, "resultid");
            return (Criteria) this;
        }

        public Criteria andResultidNotIn(List<Integer> values) {
            addCriterion("resultid not in", values, "resultid");
            return (Criteria) this;
        }

        public Criteria andResultidBetween(Integer value1, Integer value2) {
            addCriterion("resultid between", value1, value2, "resultid");
            return (Criteria) this;
        }

        public Criteria andResultidNotBetween(Integer value1, Integer value2) {
            addCriterion("resultid not between", value1, value2, "resultid");
            return (Criteria) this;
        }

        public Criteria andCourseidIsNull() {
            addCriterion("courseid is null");
            return (Criteria) this;
        }

        public Criteria andCourseidIsNotNull() {
            addCriterion("courseid is not null");
            return (Criteria) this;
        }

        public Criteria andCourseidEqualTo(Integer value) {
            addCriterion("courseid =", value, "courseid");
            return (Criteria) this;
        }

        public Criteria andCourseidNotEqualTo(Integer value) {
            addCriterion("courseid <>", value, "courseid");
            return (Criteria) this;
        }

        public Criteria andCourseidGreaterThan(Integer value) {
            addCriterion("courseid >", value, "courseid");
            return (Criteria) this;
        }

        public Criteria andCourseidGreaterThanOrEqualTo(Integer value) {
            addCriterion("courseid >=", value, "courseid");
            return (Criteria) this;
        }

        public Criteria andCourseidLessThan(Integer value) {
            addCriterion("courseid <", value, "courseid");
            return (Criteria) this;
        }

        public Criteria andCourseidLessThanOrEqualTo(Integer value) {
            addCriterion("courseid <=", value, "courseid");
            return (Criteria) this;
        }

        public Criteria andCourseidIn(List<Integer> values) {
            addCriterion("courseid in", values, "courseid");
            return (Criteria) this;
        }

        public Criteria andCourseidNotIn(List<Integer> values) {
            addCriterion("courseid not in", values, "courseid");
            return (Criteria) this;
        }

        public Criteria andCourseidBetween(Integer value1, Integer value2) {
            addCriterion("courseid between", value1, value2, "courseid");
            return (Criteria) this;
        }

        public Criteria andCourseidNotBetween(Integer value1, Integer value2) {
            addCriterion("courseid not between", value1, value2, "courseid");
            return (Criteria) this;
        }

        public Criteria andAreaidIsNull() {
            addCriterion("areaid is null");
            return (Criteria) this;
        }

        public Criteria andAreaidIsNotNull() {
            addCriterion("areaid is not null");
            return (Criteria) this;
        }

        public Criteria andAreaidEqualTo(Integer value) {
            addCriterion("areaid =", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotEqualTo(Integer value) {
            addCriterion("areaid <>", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidGreaterThan(Integer value) {
            addCriterion("areaid >", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("areaid >=", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidLessThan(Integer value) {
            addCriterion("areaid <", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidLessThanOrEqualTo(Integer value) {
            addCriterion("areaid <=", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidIn(List<Integer> values) {
            addCriterion("areaid in", values, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotIn(List<Integer> values) {
            addCriterion("areaid not in", values, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidBetween(Integer value1, Integer value2) {
            addCriterion("areaid between", value1, value2, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotBetween(Integer value1, Integer value2) {
            addCriterion("areaid not between", value1, value2, "areaid");
            return (Criteria) this;
        }

        public Criteria andCityidIsNull() {
            addCriterion("cityid is null");
            return (Criteria) this;
        }

        public Criteria andCityidIsNotNull() {
            addCriterion("cityid is not null");
            return (Criteria) this;
        }

        public Criteria andCityidEqualTo(Integer value) {
            addCriterion("cityid =", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidNotEqualTo(Integer value) {
            addCriterion("cityid <>", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidGreaterThan(Integer value) {
            addCriterion("cityid >", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cityid >=", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidLessThan(Integer value) {
            addCriterion("cityid <", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidLessThanOrEqualTo(Integer value) {
            addCriterion("cityid <=", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidIn(List<Integer> values) {
            addCriterion("cityid in", values, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidNotIn(List<Integer> values) {
            addCriterion("cityid not in", values, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidBetween(Integer value1, Integer value2) {
            addCriterion("cityid between", value1, value2, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidNotBetween(Integer value1, Integer value2) {
            addCriterion("cityid not between", value1, value2, "cityid");
            return (Criteria) this;
        }

        public Criteria andProvinceidIsNull() {
            addCriterion("provinceid is null");
            return (Criteria) this;
        }

        public Criteria andProvinceidIsNotNull() {
            addCriterion("provinceid is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceidEqualTo(Integer value) {
            addCriterion("provinceid =", value, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidNotEqualTo(Integer value) {
            addCriterion("provinceid <>", value, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidGreaterThan(Integer value) {
            addCriterion("provinceid >", value, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("provinceid >=", value, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidLessThan(Integer value) {
            addCriterion("provinceid <", value, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidLessThanOrEqualTo(Integer value) {
            addCriterion("provinceid <=", value, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidIn(List<Integer> values) {
            addCriterion("provinceid in", values, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidNotIn(List<Integer> values) {
            addCriterion("provinceid not in", values, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidBetween(Integer value1, Integer value2) {
            addCriterion("provinceid between", value1, value2, "provinceid");
            return (Criteria) this;
        }

        public Criteria andProvinceidNotBetween(Integer value1, Integer value2) {
            addCriterion("provinceid not between", value1, value2, "provinceid");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andExampeopleIsNull() {
            addCriterion("exampeople is null");
            return (Criteria) this;
        }

        public Criteria andExampeopleIsNotNull() {
            addCriterion("exampeople is not null");
            return (Criteria) this;
        }

        public Criteria andExampeopleEqualTo(Integer value) {
            addCriterion("exampeople =", value, "exampeople");
            return (Criteria) this;
        }

        public Criteria andExampeopleNotEqualTo(Integer value) {
            addCriterion("exampeople <>", value, "exampeople");
            return (Criteria) this;
        }

        public Criteria andExampeopleGreaterThan(Integer value) {
            addCriterion("exampeople >", value, "exampeople");
            return (Criteria) this;
        }

        public Criteria andExampeopleGreaterThanOrEqualTo(Integer value) {
            addCriterion("exampeople >=", value, "exampeople");
            return (Criteria) this;
        }

        public Criteria andExampeopleLessThan(Integer value) {
            addCriterion("exampeople <", value, "exampeople");
            return (Criteria) this;
        }

        public Criteria andExampeopleLessThanOrEqualTo(Integer value) {
            addCriterion("exampeople <=", value, "exampeople");
            return (Criteria) this;
        }

        public Criteria andExampeopleIn(List<Integer> values) {
            addCriterion("exampeople in", values, "exampeople");
            return (Criteria) this;
        }

        public Criteria andExampeopleNotIn(List<Integer> values) {
            addCriterion("exampeople not in", values, "exampeople");
            return (Criteria) this;
        }

        public Criteria andExampeopleBetween(Integer value1, Integer value2) {
            addCriterion("exampeople between", value1, value2, "exampeople");
            return (Criteria) this;
        }

        public Criteria andExampeopleNotBetween(Integer value1, Integer value2) {
            addCriterion("exampeople not between", value1, value2, "exampeople");
            return (Criteria) this;
        }

        public Criteria andPaymentschemeIsNull() {
            addCriterion("paymentscheme is null");
            return (Criteria) this;
        }

        public Criteria andPaymentschemeIsNotNull() {
            addCriterion("paymentscheme is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentschemeEqualTo(String value) {
            addCriterion("paymentscheme =", value, "paymentscheme");
            return (Criteria) this;
        }

        public Criteria andPaymentschemeNotEqualTo(String value) {
            addCriterion("paymentscheme <>", value, "paymentscheme");
            return (Criteria) this;
        }

        public Criteria andPaymentschemeGreaterThan(String value) {
            addCriterion("paymentscheme >", value, "paymentscheme");
            return (Criteria) this;
        }

        public Criteria andPaymentschemeGreaterThanOrEqualTo(String value) {
            addCriterion("paymentscheme >=", value, "paymentscheme");
            return (Criteria) this;
        }

        public Criteria andPaymentschemeLessThan(String value) {
            addCriterion("paymentscheme <", value, "paymentscheme");
            return (Criteria) this;
        }

        public Criteria andPaymentschemeLessThanOrEqualTo(String value) {
            addCriterion("paymentscheme <=", value, "paymentscheme");
            return (Criteria) this;
        }

        public Criteria andPaymentschemeLike(String value) {
            addCriterion("paymentscheme like", value, "paymentscheme");
            return (Criteria) this;
        }

        public Criteria andPaymentschemeNotLike(String value) {
            addCriterion("paymentscheme not like", value, "paymentscheme");
            return (Criteria) this;
        }

        public Criteria andPaymentschemeIn(List<String> values) {
            addCriterion("paymentscheme in", values, "paymentscheme");
            return (Criteria) this;
        }

        public Criteria andPaymentschemeNotIn(List<String> values) {
            addCriterion("paymentscheme not in", values, "paymentscheme");
            return (Criteria) this;
        }

        public Criteria andPaymentschemeBetween(String value1, String value2) {
            addCriterion("paymentscheme between", value1, value2, "paymentscheme");
            return (Criteria) this;
        }

        public Criteria andPaymentschemeNotBetween(String value1, String value2) {
            addCriterion("paymentscheme not between", value1, value2, "paymentscheme");
            return (Criteria) this;
        }

        public Criteria andPaymentamountIsNull() {
            addCriterion("paymentamount is null");
            return (Criteria) this;
        }

        public Criteria andPaymentamountIsNotNull() {
            addCriterion("paymentamount is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentamountEqualTo(Double value) {
            addCriterion("paymentamount =", value, "paymentamount");
            return (Criteria) this;
        }

        public Criteria andPaymentamountNotEqualTo(Double value) {
            addCriterion("paymentamount <>", value, "paymentamount");
            return (Criteria) this;
        }

        public Criteria andPaymentamountGreaterThan(Double value) {
            addCriterion("paymentamount >", value, "paymentamount");
            return (Criteria) this;
        }

        public Criteria andPaymentamountGreaterThanOrEqualTo(Double value) {
            addCriterion("paymentamount >=", value, "paymentamount");
            return (Criteria) this;
        }

        public Criteria andPaymentamountLessThan(Double value) {
            addCriterion("paymentamount <", value, "paymentamount");
            return (Criteria) this;
        }

        public Criteria andPaymentamountLessThanOrEqualTo(Double value) {
            addCriterion("paymentamount <=", value, "paymentamount");
            return (Criteria) this;
        }

        public Criteria andPaymentamountIn(List<Double> values) {
            addCriterion("paymentamount in", values, "paymentamount");
            return (Criteria) this;
        }

        public Criteria andPaymentamountNotIn(List<Double> values) {
            addCriterion("paymentamount not in", values, "paymentamount");
            return (Criteria) this;
        }

        public Criteria andPaymentamountBetween(Double value1, Double value2) {
            addCriterion("paymentamount between", value1, value2, "paymentamount");
            return (Criteria) this;
        }

        public Criteria andPaymentamountNotBetween(Double value1, Double value2) {
            addCriterion("paymentamount not between", value1, value2, "paymentamount");
            return (Criteria) this;
        }

        public Criteria andLecturepeopleIsNull() {
            addCriterion("lecturepeople is null");
            return (Criteria) this;
        }

        public Criteria andLecturepeopleIsNotNull() {
            addCriterion("lecturepeople is not null");
            return (Criteria) this;
        }

        public Criteria andLecturepeopleEqualTo(Integer value) {
            addCriterion("lecturepeople =", value, "lecturepeople");
            return (Criteria) this;
        }

        public Criteria andLecturepeopleNotEqualTo(Integer value) {
            addCriterion("lecturepeople <>", value, "lecturepeople");
            return (Criteria) this;
        }

        public Criteria andLecturepeopleGreaterThan(Integer value) {
            addCriterion("lecturepeople >", value, "lecturepeople");
            return (Criteria) this;
        }

        public Criteria andLecturepeopleGreaterThanOrEqualTo(Integer value) {
            addCriterion("lecturepeople >=", value, "lecturepeople");
            return (Criteria) this;
        }

        public Criteria andLecturepeopleLessThan(Integer value) {
            addCriterion("lecturepeople <", value, "lecturepeople");
            return (Criteria) this;
        }

        public Criteria andLecturepeopleLessThanOrEqualTo(Integer value) {
            addCriterion("lecturepeople <=", value, "lecturepeople");
            return (Criteria) this;
        }

        public Criteria andLecturepeopleIn(List<Integer> values) {
            addCriterion("lecturepeople in", values, "lecturepeople");
            return (Criteria) this;
        }

        public Criteria andLecturepeopleNotIn(List<Integer> values) {
            addCriterion("lecturepeople not in", values, "lecturepeople");
            return (Criteria) this;
        }

        public Criteria andLecturepeopleBetween(Integer value1, Integer value2) {
            addCriterion("lecturepeople between", value1, value2, "lecturepeople");
            return (Criteria) this;
        }

        public Criteria andLecturepeopleNotBetween(Integer value1, Integer value2) {
            addCriterion("lecturepeople not between", value1, value2, "lecturepeople");
            return (Criteria) this;
        }

        public Criteria andLastupdateIsNull() {
            addCriterion("lastupdate is null");
            return (Criteria) this;
        }

        public Criteria andLastupdateIsNotNull() {
            addCriterion("lastupdate is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdateEqualTo(Date value) {
            addCriterionForJDBCDate("lastupdate =", value, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("lastupdate <>", value, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateGreaterThan(Date value) {
            addCriterionForJDBCDate("lastupdate >", value, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("lastupdate >=", value, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateLessThan(Date value) {
            addCriterionForJDBCDate("lastupdate <", value, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("lastupdate <=", value, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateIn(List<Date> values) {
            addCriterionForJDBCDate("lastupdate in", values, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("lastupdate not in", values, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("lastupdate between", value1, value2, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andLastupdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("lastupdate not between", value1, value2, "lastupdate");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("isdelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("isdelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Boolean value) {
            addCriterion("isdelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Boolean value) {
            addCriterion("isdelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Boolean value) {
            addCriterion("isdelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isdelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Boolean value) {
            addCriterion("isdelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("isdelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Boolean> values) {
            addCriterion("isdelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Boolean> values) {
            addCriterion("isdelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("isdelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isdelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_info
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 02 18:00:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_info
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}