package com.woniuxy.domain;

public class SalesRole {

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_role.roleid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_role.rolename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_role.roleid
     *
     * @return the value of sales_role.roleid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_role.roleid
     *
     * @param roleid the value for sales_role.roleid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_role.rolename
     *
     * @return the value of sales_role.rolename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_role.rolename
     *
     * @param rolename the value for sales_role.rolename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
    
    @Override
   	public String toString() {
   		return "[" + rolename + "]";
   	}
}