package com.woniuxy.domain;

import java.util.Date;

public class SalesMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_message.messageid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer messageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_message.messagetheme
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String messagetheme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_message.messagetime
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Date messagetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_message.author
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_message.isSystem
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Boolean issystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_message.messagecontext
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String messagecontext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_message.messageid
     *
     * @return the value of sales_message.messageid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_message.messageid
     *
     * @param messageid the value for sales_message.messageid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setMessageid(Integer messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_message.messagetheme
     *
     * @return the value of sales_message.messagetheme
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getMessagetheme() {
        return messagetheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_message.messagetheme
     *
     * @param messagetheme the value for sales_message.messagetheme
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setMessagetheme(String messagetheme) {
        this.messagetheme = messagetheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_message.messagetime
     *
     * @return the value of sales_message.messagetime
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Date getMessagetime() {
        return messagetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_message.messagetime
     *
     * @param messagetime the value for sales_message.messagetime
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setMessagetime(Date messagetime) {
        this.messagetime = messagetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_message.author
     *
     * @return the value of sales_message.author
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_message.author
     *
     * @param author the value for sales_message.author
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setAuthor(Integer author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_message.isSystem
     *
     * @return the value of sales_message.isSystem
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Boolean getIssystem() {
        return issystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_message.isSystem
     *
     * @param issystem the value for sales_message.isSystem
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setIssystem(Boolean issystem) {
        this.issystem = issystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_message.messagecontext
     *
     * @return the value of sales_message.messagecontext
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getMessagecontext() {
        return messagecontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_message.messagecontext
     *
     * @param messagecontext the value for sales_message.messagecontext
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setMessagecontext(String messagecontext) {
        this.messagecontext = messagecontext;
    }
}