package com.woniuxy.domain;

public class SalesTreeRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_tree_role.roleid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_tree_role.treeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer treeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_tree_role.roleid
     *
     * @return the value of sales_tree_role.roleid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_tree_role.roleid
     *
     * @param roleid the value for sales_tree_role.roleid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_tree_role.treeid
     *
     * @return the value of sales_tree_role.treeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getTreeid() {
        return treeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_tree_role.treeid
     *
     * @param treeid the value for sales_tree_role.treeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setTreeid(Integer treeid) {
        this.treeid = treeid;
    }
}