package com.woniuxy.domain;

public class SalesUserMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_user_message.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_user_message.messageid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer messageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_user_message.isread
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Boolean isread;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_user_message.uid
     *
     * @return the value of sales_user_message.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_user_message.uid
     *
     * @param uid the value for sales_user_message.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_user_message.messageid
     *
     * @return the value of sales_user_message.messageid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_user_message.messageid
     *
     * @param messageid the value for sales_user_message.messageid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setMessageid(Integer messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_user_message.isread
     *
     * @return the value of sales_user_message.isread
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Boolean getIsread() {
        return isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_user_message.isread
     *
     * @param isread the value for sales_user_message.isread
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setIsread(Boolean isread) {
        this.isread = isread;
    }
}