package com.woniuxy.domain;

public class SalesArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_area.aid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_area.areaid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_area.AREA
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_area.father
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String father;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_area.aid
     *
     * @return the value of sales_area.aid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_area.aid
     *
     * @param aid the value for sales_area.aid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_area.areaid
     *
     * @return the value of sales_area.areaid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_area.areaid
     *
     * @param areaid the value for sales_area.areaid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_area.AREA
     *
     * @return the value of sales_area.AREA
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_area.AREA
     *
     * @param area the value for sales_area.AREA
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_area.father
     *
     * @return the value of sales_area.father
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getFather() {
        return father;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_area.father
     *
     * @param father the value for sales_area.father
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setFather(String father) {
        this.father = father;
    }
}