package com.woniuxy.domain;

public class SalesCity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_city.cid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_city.cityid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_city.city
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_city.father
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String father;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_city.cid
     *
     * @return the value of sales_city.cid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_city.cid
     *
     * @param cid the value for sales_city.cid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_city.cityid
     *
     * @return the value of sales_city.cityid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_city.cityid
     *
     * @param cityid the value for sales_city.cityid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setCityid(String cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_city.city
     *
     * @return the value of sales_city.city
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_city.city
     *
     * @param city the value for sales_city.city
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_city.father
     *
     * @return the value of sales_city.father
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getFather() {
        return father;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_city.father
     *
     * @param father the value for sales_city.father
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setFather(String father) {
        this.father = father;
    }
}