package com.woniuxy.domain;

import java.util.Date;
import java.util.List;

public class SalesUserinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_userinfo.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer uid;
    
    private List<SalesRole> salesRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_userinfo.uname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_userinfo.truename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_userinfo.upass
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String upass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_userinfo.photo
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_userinfo.lastlogintime
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Date lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_userinfo.isdisplay
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Boolean isdisplay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_userinfo.uid
     *
     * @return the value of sales_userinfo.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_userinfo.uid
     *
     * @param uid the value for sales_userinfo.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_userinfo.uname
     *
     * @return the value of sales_userinfo.uname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_userinfo.uname
     *
     * @param uname the value for sales_userinfo.uname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_userinfo.truename
     *
     * @return the value of sales_userinfo.truename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_userinfo.truename
     *
     * @param truename the value for sales_userinfo.truename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_userinfo.upass
     *
     * @return the value of sales_userinfo.upass
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getUpass() {
        return upass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_userinfo.upass
     *
     * @param upass the value for sales_userinfo.upass
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setUpass(String upass) {
        this.upass = upass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_userinfo.photo
     *
     * @return the value of sales_userinfo.photo
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_userinfo.photo
     *
     * @param photo the value for sales_userinfo.photo
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_userinfo.lastlogintime
     *
     * @return the value of sales_userinfo.lastlogintime
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_userinfo.lastlogintime
     *
     * @param lastlogintime the value for sales_userinfo.lastlogintime
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_userinfo.isdisplay
     *
     * @return the value of sales_userinfo.isdisplay
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Boolean getIsdisplay() {
        return isdisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_userinfo.isdisplay
     *
     * @param isdisplay the value for sales_userinfo.isdisplay
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setIsdisplay(Boolean isdisplay) {
        this.isdisplay = isdisplay;
    }

	public List<SalesRole> getSalesRole() {
		return salesRole;
	}

	public void setSalesRole(List<SalesRole> salesRole) {
		this.salesRole = salesRole;
	}

	
    
}