package com.woniuxy.domain;

public class SalesRelatedperson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_relatedperson.relatedpersonid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer relatedpersonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_relatedperson.relatedpersonname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String relatedpersonname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_relatedperson.role
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Boolean role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_relatedperson.isdelete
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Boolean isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_relatedperson.relatedpersonid
     *
     * @return the value of sales_relatedperson.relatedpersonid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getRelatedpersonid() {
        return relatedpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_relatedperson.relatedpersonid
     *
     * @param relatedpersonid the value for sales_relatedperson.relatedpersonid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setRelatedpersonid(Integer relatedpersonid) {
        this.relatedpersonid = relatedpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_relatedperson.relatedpersonname
     *
     * @return the value of sales_relatedperson.relatedpersonname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getRelatedpersonname() {
        return relatedpersonname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_relatedperson.relatedpersonname
     *
     * @param relatedpersonname the value for sales_relatedperson.relatedpersonname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setRelatedpersonname(String relatedpersonname) {
        this.relatedpersonname = relatedpersonname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_relatedperson.role
     *
     * @return the value of sales_relatedperson.role
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Boolean getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_relatedperson.role
     *
     * @param role the value for sales_relatedperson.role
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setRole(Boolean role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_relatedperson.isdelete
     *
     * @return the value of sales_relatedperson.isdelete
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_relatedperson.isdelete
     *
     * @param isdelete the value for sales_relatedperson.isdelete
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }
}