package com.woniuxy.domain;

public class SalesUserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_user_role.roleid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_user_role.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_user_role.roleid
     *
     * @return the value of sales_user_role.roleid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_user_role.roleid
     *
     * @param roleid the value for sales_user_role.roleid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_user_role.uid
     *
     * @return the value of sales_user_role.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_user_role.uid
     *
     * @param uid the value for sales_user_role.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}