package com.woniuxy.domain;

public class SalesProvince {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_province.pid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_province.provinceid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_province.province
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String province;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_province.pid
     *
     * @return the value of sales_province.pid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_province.pid
     *
     * @param pid the value for sales_province.pid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_province.provinceid
     *
     * @return the value of sales_province.provinceid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_province.provinceid
     *
     * @param provinceid the value for sales_province.provinceid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_province.province
     *
     * @return the value of sales_province.province
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_province.province
     *
     * @param province the value for sales_province.province
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setProvince(String province) {
        this.province = province;
    }
}