package com.woniuxy.domain;

import java.util.Date;

public class SaleInfodetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_infodetail.infoid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer infoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_infodetail.school
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_infodetail.major
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_infodetail.planjoindate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Date planjoindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_infodetail.realdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Date realdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_infodetail.isexam
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Boolean isexam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_infodetail.ordersetdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Date ordersetdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_infodetail.classesdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Date classesdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_infodetail.submitdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Date submitdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_infodetail.joindate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Date joindate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_infodetail.infoid
     *
     * @return the value of sale_infodetail.infoid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getInfoid() {
        return infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_infodetail.infoid
     *
     * @param infoid the value for sale_infodetail.infoid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setInfoid(Integer infoid) {
        this.infoid = infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_infodetail.school
     *
     * @return the value of sale_infodetail.school
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_infodetail.school
     *
     * @param school the value for sale_infodetail.school
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_infodetail.major
     *
     * @return the value of sale_infodetail.major
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_infodetail.major
     *
     * @param major the value for sale_infodetail.major
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_infodetail.planjoindate
     *
     * @return the value of sale_infodetail.planjoindate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Date getPlanjoindate() {
        return planjoindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_infodetail.planjoindate
     *
     * @param planjoindate the value for sale_infodetail.planjoindate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setPlanjoindate(Date planjoindate) {
        this.planjoindate = planjoindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_infodetail.realdate
     *
     * @return the value of sale_infodetail.realdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Date getRealdate() {
        return realdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_infodetail.realdate
     *
     * @param realdate the value for sale_infodetail.realdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setRealdate(Date realdate) {
        this.realdate = realdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_infodetail.isexam
     *
     * @return the value of sale_infodetail.isexam
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Boolean getIsexam() {
        return isexam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_infodetail.isexam
     *
     * @param isexam the value for sale_infodetail.isexam
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setIsexam(Boolean isexam) {
        this.isexam = isexam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_infodetail.ordersetdate
     *
     * @return the value of sale_infodetail.ordersetdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Date getOrdersetdate() {
        return ordersetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_infodetail.ordersetdate
     *
     * @param ordersetdate the value for sale_infodetail.ordersetdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setOrdersetdate(Date ordersetdate) {
        this.ordersetdate = ordersetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_infodetail.classesdate
     *
     * @return the value of sale_infodetail.classesdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Date getClassesdate() {
        return classesdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_infodetail.classesdate
     *
     * @param classesdate the value for sale_infodetail.classesdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setClassesdate(Date classesdate) {
        this.classesdate = classesdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_infodetail.submitdate
     *
     * @return the value of sale_infodetail.submitdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Date getSubmitdate() {
        return submitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_infodetail.submitdate
     *
     * @param submitdate the value for sale_infodetail.submitdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setSubmitdate(Date submitdate) {
        this.submitdate = submitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_infodetail.joindate
     *
     * @return the value of sale_infodetail.joindate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Date getJoindate() {
        return joindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_infodetail.joindate
     *
     * @param joindate the value for sale_infodetail.joindate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setJoindate(Date joindate) {
        this.joindate = joindate;
    }
}