package com.woniuxy.domain;

import java.io.Serializable;
import java.util.Date;

public class SaleInfo implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.infoid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private  Integer infoid;
    
    private SalesDegree salesDegree;
    
    private SalesComefrom salesComfrom;
    
    private SalesInfotype salesInfotype;
    
    public SalesInfotype getSalesInfotype() {
		return salesInfotype;
	}

	public void setSalesInfotype(SalesInfotype salesInfotype) {
		this.salesInfotype = salesInfotype;
	}

	public SalesComefrom getSalesComfrom() {
		return salesComfrom;
	}

	public void setSalesComfrom(SalesComefrom salesComfrom) {
		this.salesComfrom = salesComfrom;
	}

	public SalesDegree getSalesDegree() {
		return salesDegree;
	}

	public void setSalesDegree(SalesDegree salesDegree) {
		this.salesDegree = salesDegree;
	}



	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.infoname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String infoname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.infonamepinyin
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String infonamepinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.sex
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.age
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.degreeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer degreeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.tel
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.comefromid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer comefromid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.infotypeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer infotypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.returndate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Date returndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.beforepeople
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer beforepeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.afterpeople
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer afterpeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.beforetmk
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer beforetmk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.returnid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer returnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.infodate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Date infodate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.distributiondate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Date distributiondate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.resultid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer resultid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.courseid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.areaid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.cityid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.provinceid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.address
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.exampeople
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer exampeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.paymentscheme
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String paymentscheme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.paymentamount
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Double paymentamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.lecturepeople
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer lecturepeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.lastupdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Date lastupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_info.isdelete
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Boolean isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.infoid
     *
     * @return the value of sale_info.infoid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getInfoid() {
        return infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.infoid
     *
     * @param infoid the value for sale_info.infoid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setInfoid(Integer infoid) {
        this.infoid = infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.infoname
     *
     * @return the value of sale_info.infoname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getInfoname() {
        return infoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.infoname
     *
     * @param infoname the value for sale_info.infoname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setInfoname(String infoname) {
        this.infoname = infoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.infonamepinyin
     *
     * @return the value of sale_info.infonamepinyin
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getInfonamepinyin() {
        return infonamepinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.infonamepinyin
     *
     * @param infonamepinyin the value for sale_info.infonamepinyin
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setInfonamepinyin(String infonamepinyin) {
        this.infonamepinyin = infonamepinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.sex
     *
     * @return the value of sale_info.sex
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.sex
     *
     * @param sex the value for sale_info.sex
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.age
     *
     * @return the value of sale_info.age
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.age
     *
     * @param age the value for sale_info.age
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.degreeid
     *
     * @return the value of sale_info.degreeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getDegreeid() {
        return degreeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.degreeid
     *
     * @param degreeid the value for sale_info.degreeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setDegreeid(Integer degreeid) {
        this.degreeid = degreeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.tel
     *
     * @return the value of sale_info.tel
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.tel
     *
     * @param tel the value for sale_info.tel
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.comefromid
     *
     * @return the value of sale_info.comefromid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getComefromid() {
        return comefromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.comefromid
     *
     * @param comefromid the value for sale_info.comefromid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setComefromid(Integer comefromid) {
        this.comefromid = comefromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.infotypeid
     *
     * @return the value of sale_info.infotypeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getInfotypeid() {
        return infotypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.infotypeid
     *
     * @param infotypeid the value for sale_info.infotypeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setInfotypeid(Integer infotypeid) {
        this.infotypeid = infotypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.uid
     *
     * @return the value of sale_info.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.uid
     *
     * @param uid the value for sale_info.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.returndate
     *
     * @return the value of sale_info.returndate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Date getReturndate() {
        return returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.returndate
     *
     * @param returndate the value for sale_info.returndate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setReturndate(Date returndate) {
        this.returndate = returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.beforepeople
     *
     * @return the value of sale_info.beforepeople
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getBeforepeople() {
        return beforepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.beforepeople
     *
     * @param beforepeople the value for sale_info.beforepeople
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setBeforepeople(Integer beforepeople) {
        this.beforepeople = beforepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.afterpeople
     *
     * @return the value of sale_info.afterpeople
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getAfterpeople() {
        return afterpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.afterpeople
     *
     * @param afterpeople the value for sale_info.afterpeople
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setAfterpeople(Integer afterpeople) {
        this.afterpeople = afterpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.beforetmk
     *
     * @return the value of sale_info.beforetmk
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getBeforetmk() {
        return beforetmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.beforetmk
     *
     * @param beforetmk the value for sale_info.beforetmk
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setBeforetmk(Integer beforetmk) {
        this.beforetmk = beforetmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.returnid
     *
     * @return the value of sale_info.returnid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getReturnid() {
        return returnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.returnid
     *
     * @param returnid the value for sale_info.returnid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setReturnid(Integer returnid) {
        this.returnid = returnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.infodate
     *
     * @return the value of sale_info.infodate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Date getInfodate() {
        return infodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.infodate
     *
     * @param infodate the value for sale_info.infodate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setInfodate(Date infodate) {
        this.infodate = infodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.distributiondate
     *
     * @return the value of sale_info.distributiondate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Date getDistributiondate() {
        return distributiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.distributiondate
     *
     * @param distributiondate the value for sale_info.distributiondate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setDistributiondate(Date distributiondate) {
        this.distributiondate = distributiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.resultid
     *
     * @return the value of sale_info.resultid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getResultid() {
        return resultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.resultid
     *
     * @param resultid the value for sale_info.resultid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setResultid(Integer resultid) {
        this.resultid = resultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.courseid
     *
     * @return the value of sale_info.courseid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.courseid
     *
     * @param courseid the value for sale_info.courseid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.areaid
     *
     * @return the value of sale_info.areaid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.areaid
     *
     * @param areaid the value for sale_info.areaid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.cityid
     *
     * @return the value of sale_info.cityid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.cityid
     *
     * @param cityid the value for sale_info.cityid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.provinceid
     *
     * @return the value of sale_info.provinceid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.provinceid
     *
     * @param provinceid the value for sale_info.provinceid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.address
     *
     * @return the value of sale_info.address
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.address
     *
     * @param address the value for sale_info.address
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.exampeople
     *
     * @return the value of sale_info.exampeople
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getExampeople() {
        return exampeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.exampeople
     *
     * @param exampeople the value for sale_info.exampeople
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setExampeople(Integer exampeople) {
        this.exampeople = exampeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.paymentscheme
     *
     * @return the value of sale_info.paymentscheme
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getPaymentscheme() {
        return paymentscheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.paymentscheme
     *
     * @param paymentscheme the value for sale_info.paymentscheme
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setPaymentscheme(String paymentscheme) {
        this.paymentscheme = paymentscheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.paymentamount
     *
     * @return the value of sale_info.paymentamount
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Double getPaymentamount() {
        return paymentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.paymentamount
     *
     * @param paymentamount the value for sale_info.paymentamount
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setPaymentamount(Double paymentamount) {
        this.paymentamount = paymentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.lecturepeople
     *
     * @return the value of sale_info.lecturepeople
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getLecturepeople() {
        return lecturepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.lecturepeople
     *
     * @param lecturepeople the value for sale_info.lecturepeople
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setLecturepeople(Integer lecturepeople) {
        this.lecturepeople = lecturepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.lastupdate
     *
     * @return the value of sale_info.lastupdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.lastupdate
     *
     * @param lastupdate the value for sale_info.lastupdate
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_info.isdelete
     *
     * @return the value of sale_info.isdelete
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_info.isdelete
     *
     * @param isdelete the value for sale_info.isdelete
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

	@Override
	public String toString() {
		return "SaleInfo [infoid=" + infoid + ", infoname=" + infoname + ", infonamepinyin=" + infonamepinyin + ", sex="
				+ sex + ", age=" + age + ", degreeid=" + degreeid + ", tel=" + tel + ", comefromid=" + comefromid
				+ ", infotypeid=" + infotypeid + ", uid=" + uid + ", returndate=" + returndate + ", beforepeople="
				+ beforepeople + ", afterpeople=" + afterpeople + ", beforetmk=" + beforetmk + ", returnid=" + returnid
				+ ", infodate=" + infodate + ", distributiondate=" + distributiondate + ", resultid=" + resultid
				+ ", courseid=" + courseid + ", areaid=" + areaid + ", cityid=" + cityid + ", provinceid=" + provinceid
				+ ", address=" + address + ", exampeople=" + exampeople + ", paymentscheme=" + paymentscheme
				+ ", paymentamount=" + paymentamount + ", lecturepeople=" + lecturepeople + ", lastupdate=" + lastupdate
				+ ", isdelete=" + isdelete + "]";
	}
    
}