package com.woniuxy.domain;

import java.util.ArrayList;
import java.util.List;

public class SalesInfotypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public SalesInfotypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInfotypeidIsNull() {
            addCriterion("infotypeid is null");
            return (Criteria) this;
        }

        public Criteria andInfotypeidIsNotNull() {
            addCriterion("infotypeid is not null");
            return (Criteria) this;
        }

        public Criteria andInfotypeidEqualTo(Integer value) {
            addCriterion("infotypeid =", value, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidNotEqualTo(Integer value) {
            addCriterion("infotypeid <>", value, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidGreaterThan(Integer value) {
            addCriterion("infotypeid >", value, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("infotypeid >=", value, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidLessThan(Integer value) {
            addCriterion("infotypeid <", value, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidLessThanOrEqualTo(Integer value) {
            addCriterion("infotypeid <=", value, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidIn(List<Integer> values) {
            addCriterion("infotypeid in", values, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidNotIn(List<Integer> values) {
            addCriterion("infotypeid not in", values, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidBetween(Integer value1, Integer value2) {
            addCriterion("infotypeid between", value1, value2, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("infotypeid not between", value1, value2, "infotypeid");
            return (Criteria) this;
        }

        public Criteria andInfotypenameIsNull() {
            addCriterion("infotypename is null");
            return (Criteria) this;
        }

        public Criteria andInfotypenameIsNotNull() {
            addCriterion("infotypename is not null");
            return (Criteria) this;
        }

        public Criteria andInfotypenameEqualTo(String value) {
            addCriterion("infotypename =", value, "infotypename");
            return (Criteria) this;
        }

        public Criteria andInfotypenameNotEqualTo(String value) {
            addCriterion("infotypename <>", value, "infotypename");
            return (Criteria) this;
        }

        public Criteria andInfotypenameGreaterThan(String value) {
            addCriterion("infotypename >", value, "infotypename");
            return (Criteria) this;
        }

        public Criteria andInfotypenameGreaterThanOrEqualTo(String value) {
            addCriterion("infotypename >=", value, "infotypename");
            return (Criteria) this;
        }

        public Criteria andInfotypenameLessThan(String value) {
            addCriterion("infotypename <", value, "infotypename");
            return (Criteria) this;
        }

        public Criteria andInfotypenameLessThanOrEqualTo(String value) {
            addCriterion("infotypename <=", value, "infotypename");
            return (Criteria) this;
        }

        public Criteria andInfotypenameLike(String value) {
            addCriterion("infotypename like", value, "infotypename");
            return (Criteria) this;
        }

        public Criteria andInfotypenameNotLike(String value) {
            addCriterion("infotypename not like", value, "infotypename");
            return (Criteria) this;
        }

        public Criteria andInfotypenameIn(List<String> values) {
            addCriterion("infotypename in", values, "infotypename");
            return (Criteria) this;
        }

        public Criteria andInfotypenameNotIn(List<String> values) {
            addCriterion("infotypename not in", values, "infotypename");
            return (Criteria) this;
        }

        public Criteria andInfotypenameBetween(String value1, String value2) {
            addCriterion("infotypename between", value1, value2, "infotypename");
            return (Criteria) this;
        }

        public Criteria andInfotypenameNotBetween(String value1, String value2) {
            addCriterion("infotypename not between", value1, value2, "infotypename");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sales_infotype
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 02 18:00:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sales_infotype
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}