package com.woniuxy.domain;

public class SalesComefrom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_comefrom.comefromid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer comefromid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_comefrom.comefromname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String comefromname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_comefrom.comefromid
     *
     * @return the value of sales_comefrom.comefromid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getComefromid() {
        return comefromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_comefrom.comefromid
     *
     * @param comefromid the value for sales_comefrom.comefromid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setComefromid(Integer comefromid) {
        this.comefromid = comefromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_comefrom.comefromname
     *
     * @return the value of sales_comefrom.comefromname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getComefromname() {
        return comefromname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_comefrom.comefromname
     *
     * @param comefromname the value for sales_comefrom.comefromname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setComefromname(String comefromname) {
        this.comefromname = comefromname;
    }
}