package com.woniuxy.domain;

public class SalesResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_result.resultid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer resultid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_result.resultname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String resultname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_result.resultid
     *
     * @return the value of sales_result.resultid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getResultid() {
        return resultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_result.resultid
     *
     * @param resultid the value for sales_result.resultid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setResultid(Integer resultid) {
        this.resultid = resultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_result.resultname
     *
     * @return the value of sales_result.resultname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getResultname() {
        return resultname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_result.resultname
     *
     * @param resultname the value for sales_result.resultname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setResultname(String resultname) {
        this.resultname = resultname;
    }
}