package com.woniuxy.domain;

import java.io.Serializable;

public class SalesDegree implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_degree.degreeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer degreeid;
    
    @Override
	public String toString() {
		return degreename;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_degree.degreename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String degreename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_degree.degreeid
     *
     * @return the value of sales_degree.degreeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getDegreeid() {
        return degreeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_degree.degreeid
     *
     * @param degreeid the value for sales_degree.degreeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setDegreeid(Integer degreeid) {
        this.degreeid = degreeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_degree.degreename
     *
     * @return the value of sales_degree.degreename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getDegreename() {
        return degreename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_degree.degreename
     *
     * @param degreename the value for sales_degree.degreename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setDegreename(String degreename) {
        this.degreename = degreename;
    }
}