package com.woniuxy.domain;

public class SalesCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_course.courseid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_course.coursename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String coursename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_course.courseid
     *
     * @return the value of sales_course.courseid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_course.courseid
     *
     * @param courseid the value for sales_course.courseid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_course.coursename
     *
     * @return the value of sales_course.coursename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_course.coursename
     *
     * @param coursename the value for sales_course.coursename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }
}