package com.woniuxy.domain;

public class SalesReturn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_return.returnid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer returnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_return.returnname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String returnname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_return.returnid
     *
     * @return the value of sales_return.returnid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getReturnid() {
        return returnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_return.returnid
     *
     * @param returnid the value for sales_return.returnid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setReturnid(Integer returnid) {
        this.returnid = returnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_return.returnname
     *
     * @return the value of sales_return.returnname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getReturnname() {
        return returnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_return.returnname
     *
     * @param returnname the value for sales_return.returnname
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setReturnname(String returnname) {
        this.returnname = returnname;
    }
}