package com.woniuxy.domain;

public class SalesInfotype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_infotype.infotypeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer infotypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_infotype.infotypename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String infotypename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_infotype.infotypeid
     *
     * @return the value of sales_infotype.infotypeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getInfotypeid() {
        return infotypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_infotype.infotypeid
     *
     * @param infotypeid the value for sales_infotype.infotypeid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setInfotypeid(Integer infotypeid) {
        this.infotypeid = infotypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_infotype.infotypename
     *
     * @return the value of sales_infotype.infotypename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getInfotypename() {
        return infotypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_infotype.infotypename
     *
     * @param infotypename the value for sales_infotype.infotypename
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setInfotypename(String infotypename) {
        this.infotypename = infotypename;
    }
}