package com.woniuxy.domain;

import java.util.Date;

public class SaleVisit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_visit.visitid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer visitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_visit.resultid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer resultid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_visit.visittime
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Date visittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_visit.visitcontext
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private String visitcontext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_visit.infoid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer infoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_visit.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_visit.visitid
     *
     * @return the value of sale_visit.visitid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getVisitid() {
        return visitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_visit.visitid
     *
     * @param visitid the value for sale_visit.visitid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setVisitid(Integer visitid) {
        this.visitid = visitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_visit.resultid
     *
     * @return the value of sale_visit.resultid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getResultid() {
        return resultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_visit.resultid
     *
     * @param resultid the value for sale_visit.resultid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setResultid(Integer resultid) {
        this.resultid = resultid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_visit.visittime
     *
     * @return the value of sale_visit.visittime
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Date getVisittime() {
        return visittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_visit.visittime
     *
     * @param visittime the value for sale_visit.visittime
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setVisittime(Date visittime) {
        this.visittime = visittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_visit.visitcontext
     *
     * @return the value of sale_visit.visitcontext
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public String getVisitcontext() {
        return visitcontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_visit.visitcontext
     *
     * @param visitcontext the value for sale_visit.visitcontext
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setVisitcontext(String visitcontext) {
        this.visitcontext = visitcontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_visit.infoid
     *
     * @return the value of sale_visit.infoid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getInfoid() {
        return infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_visit.infoid
     *
     * @param infoid the value for sale_visit.infoid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setInfoid(Integer infoid) {
        this.infoid = infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_visit.uid
     *
     * @return the value of sale_visit.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_visit.uid
     *
     * @param uid the value for sale_visit.uid
     *
     * @mbggenerated Wed Jan 02 18:00:43 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}